# Generated by Django 3.2.6 on 2021-12-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210722_1259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classsubjects',
            options={'ordering': ['class_num'], 'verbose_name': 'Предмети класу', 'verbose_name_plural': 'Предмети класу'},
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.CharField(choices=[('1', '1 група'), ('2', '2 група')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
