# Generated by Django 3.2.6 on 2021-12-11 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20211210_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsubjects',
            name='hasGroup',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
