# Generated by Django 3.2.5 on 2021-07-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_rename_data_teacher_date1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='user_id'),
        ),
    ]
