# Generated by Django 3.2.5 on 2021-07-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_teacher_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='user_id'),
        ),
    ]
