# Generated by Django 3.2.5 on 2021-07-20 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_alter_teacher_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='date1',
            new_name='date',
        ),
    ]
