# Generated by Django 3.2.5 on 2021-07-22 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0013_classteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.subject', verbose_name='Предмет'),
        ),
    ]
