# Generated by Django 3.2.5 on 2021-07-23 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210722_1259'),
        ('teachers', '0017_alter_classteacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='journal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_journal', to='students.schooljournal', verbose_name='Журнал'),
        ),
    ]
