# Generated by Django 3.2.5 on 2021-07-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0018_alter_classteacher_journal_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True, verbose_name='Тип оцінки')),
            ],
            options={
                'verbose_name': 'Тип оцінки',
                'verbose_name_plural': 'Типи оцінки',
                'ordering': ['type'],
            },
        ),
        migrations.AlterModelOptions(
            name='classteacher',
            options={'ordering': ['journal_id'], 'verbose_name': 'Предмет вчителя', 'verbose_name_plural': 'Предмети вчителів'},
        ),
    ]
