# Generated by Django 3.2.5 on 2021-08-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210722_1259'),
        ('teachers', '0020_mark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(max_length=50, verbose_name='Тема')),
                ('start', models.DateField(verbose_name='Дата початку')),
                ('finish', models.DateField(blank=True, null=True, verbose_name='Дата закінченя')),
            ],
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'ordering': ['type'], 'verbose_name': 'Оцінка', 'verbose_name_plural': 'Оцінки'},
        ),
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mark_id', to='students.student', verbose_name='Учень'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_mark_id', to='teachers.classteacher', verbose_name='Вчитель'),
        ),
        migrations.AddField(
            model_name='mark',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_id', to='teachers.topic', verbose_name='Тема'),
        ),
    ]
