# Generated by Django 3.2.5 on 2021-08-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0022_auto_20210801_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='class_teacher',
            field=models.CharField(max_length=5, verbose_name='Вчитель'),
        ),
    ]
