# Generated by Django 3.2.5 on 2021-08-05 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0025_remove_topic_class_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_choice', to='teachers.classteacher', verbose_name='Вчитель'),
        ),
    ]
