# Generated by Django 3.2.6 on 2021-08-12 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0027_alter_mark_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='type_id', to='teachers.topic', verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='class_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_choice', to='teachers.classteacher', verbose_name='Вчитель'),
        ),
    ]
