# Generated by Django 3.2.6 on 2021-08-12 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0028_auto_20210812_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(verbose_name='Дата початку')),
                ('finish', models.DateField(verbose_name='Дата закінченя')),
                ('class_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_select', to='teachers.classteacher', verbose_name='Вчитель')),
            ],
            options={
                'verbose_name': 'Семестр',
                'verbose_name_plural': 'Семестри',
                'ordering': ['class_teacher'],
            },
        ),
    ]
