# Generated by Django 3.2.6 on 2021-08-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0029_auto_20210812_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='semester_select', to='teachers.marktype', verbose_name='Семестр'),
            preserve_default=False,
        ),
    ]
