# Generated by Django 3.2.6 on 2021-08-12 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0030_semester_semester'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['semester'], 'verbose_name': 'Семестр', 'verbose_name_plural': 'Семестри'},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='class_teacher',
        ),
    ]
