# Generated by Django 3.2.6 on 2021-12-10 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0032_alter_topic_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersubjects',
            options={'verbose_name': 'Сиписок предметів', 'verbose_name_plural': 'Сиписок предметів'},
        ),
    ]
