# Generated by Django 3.2.6 on 2021-12-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0033_alter_teachersubjects_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='classteacher',
            name='group',
            field=models.CharField(choices=[('1', '1 група'), ('2', '2 група')], max_length=50, null=True),
        ),
    ]
