# Generated by Django 3.2.6 on 2021-12-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0034_classteacher_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='group',
            field=models.CharField(blank=True, choices=[('1', '1 група'), ('2', '2 група')], max_length=50, null=True),
        ),
    ]
