# Generated by Django 3.2.6 on 2021-12-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0035_alter_classteacher_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='group',
            field=models.BooleanField(default=False, verbose_name='Ділеться на групи'),
            preserve_default=False,
        ),
    ]
