# Generated by Django 3.2.5 on 2021-07-19 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='data',
            new_name='date1',
        ),
    ]
