# Generated by Django 3.2.5 on 2021-07-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0010_alter_teacher_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersubjects',
            name='teacher_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_id_set', to='teachers.teacher', verbose_name='Teacher ID'),
        ),
    ]
