# Generated by Django 3.2.5 on 2021-07-22 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210722_1259'),
        ('teachers', '0012_alter_teachersubjects_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.schooljournal', verbose_name='Журнал')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.classsubjects', verbose_name='Предмет')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Вчитель')),
            ],
            options={
                'verbose_name': 'Предмет вчителя',
                'verbose_name_plural': 'Предмет вчителя',
            },
        ),
    ]
