# Generated by Django 3.2.5 on 2021-07-23 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20210722_1259'),
        ('teachers', '0014_alter_classteacher_subject_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='journal_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='students.schooljournal', verbose_name='Журнал'),
        ),
    ]
