# Generated by Django 3.2.5 on 2021-07-23 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0016_auto_20210723_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteacher',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher', to='teachers.teachersubjects', verbose_name='Вчитель'),
        ),
    ]
