# Generated by Django 3.2.5 on 2021-08-01 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0021_auto_20210801_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['topic'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Теми'},
        ),
        migrations.AddField(
            model_name='topic',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_teacher_choice', to='teachers.classteacher', verbose_name='Вчитель'),
        ),
    ]
