# Generated by Django 3.2.6 on 2021-08-10 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0026_topic_class_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='topic',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='type_id', to='teachers.topic', verbose_name='Тема'),
            preserve_default=False,
        ),
    ]
