# Generated by Django 3.2.5 on 2021-07-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0011_alter_teachersubjects_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.IntegerField(max_length=2, verbose_name='Номер класса')),
                ('class_letter', models.CharField(max_length=1, verbose_name='Буква класса')),
                ('year', models.DateField(max_length=50, verbose_name='Навчальний рік')),
                ('class_teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher', verbose_name='Teacher ID')),
            ],
            options={
                'verbose_name': 'Журнал',
                'verbose_name_plural': 'Журнали',
            },
        ),
    ]
