# Generated by Django 3.2.5 on 2021-07-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooljournal',
            name='class_num',
            field=models.IntegerField(verbose_name='Номер класса'),
        ),
    ]
