# Generated by Django 3.2.5 on 2021-07-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0012_alter_teachersubjects_teacher_id'),
        ('students', '0003_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['so_name'], 'verbose_name': 'Учень', 'verbose_name_plural': 'Учні'},
        ),
        migrations.AlterField(
            model_name='schooljournal',
            name='class_num',
            field=models.PositiveSmallIntegerField(verbose_name='Номер класса'),
        ),
        migrations.CreateModel(
            name='ClassSubjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_num', models.PositiveSmallIntegerField(unique=True, verbose_name='Номер классу')),
                ('subjects', models.ManyToManyField(to='teachers.Subject', verbose_name='Предмети')),
            ],
            options={
                'verbose_name': 'Предмети классу',
                'verbose_name_plural': 'Предмети классу',
                'ordering': ['class_num'],
            },
        ),
    ]
